
FDI_COLUMNS = {
    'Año': 'year',
    'Año de materialización': 'year',
    'Trimestre': 'quarter_id',
    'Trimestre de materialización':  'quarter_id',
    'Tipo de inversión': 'investment_type',
    'Inversión': 'investment_type',
    'Inversión Genérica': 'investment_type',
    'Sector': 'sector_id',
    'Subsector': 'subsector_id',
    'Rama': 'industry_group_id',
    'País de Origen DEAE': 'country_id',
    'País de Origen_otros': 'country_id',
    'País': 'country_id',
    'Entidad federativa': 'ent_id',
    'Monto': 'value',
    'Suma de Monto en millones': 'value',
    'Recuento': 'count',
    'Recuento distinto de Expediente': 'count',
    'Monto C': 'value_c'
    'monto cuentas entre compañías': 'value_between_companies',
    'monto nuevas inversiones': 'value_new_investments',
    'monto reinversión de utilidades': 'value_re_investments',
    'recuento cuentas entre compañías': 'count_between_companies',
    'recuento nuevas inversiones': 'count_new_investments',
    'recuento reinversión de utilidades': 'count_re_investments',
    'monto C cuentas entre compañías': 'value_between_companies_c',
    'monto C nuevas inversiones': 'value_new_investments_c',
    'monto C reinversión de utilidades': 'value_re_investments_c'
}