from bamboo_lib.helpers import query_to_df
from bamboo_lib.connectors.models import Connector

rename_columns = {
    'fecha_actualizacion': 'updated_date',
    'origen': 'origin',
    'sector': 'type_health_institution_attended',
    'entidad_um': 'health_institution_attended_ent',
    'sexo': 'sex',
    'entidad_nac': 'patient_origin_ent_id',
    'tipo_paciente': 'patient_type',
    'fecha_ingreso': 'ingress_date',
    'fecha_sintomas': 'symptoms_date',
    'fecha_def': 'death_date',
    'intubado': 'intubated',
    'neumonia': 'pneumonia_diagnose',
    'edad': 'age',
    'nacionalidad': 'nationality',
    'embarazo': 'pregnancy',
    'habla_lengua_indig': 'speaks_indigenous_language',
    'diabetes': 'diabetes_diagnose',
    'epoc': 'COPD_diagnose',
    'asma': 'asthma_diagnose',
    'inmusupr': 'inmunosupresion_diagnose',
    'hipertension': 'hypertension_diagnose',
    'otra_com': 'diagnosis_another_disease',
    'cardiovascular': 'cardiovascular_diagnose',
    'obesidad': 'obesity_diagnose',
    'renal_cronica': 'chronic_kidney_failure_diagnose',
    'tabaquismo': 'smoking_diagnose',
    'otro_caso': 'contact_another_covid_case',
    'resultado_lab': 'covid_positive',
    'migrante': 'migrant',
    'pais_nacionalidad': 'country_nationality',
    'pais_origen': 'country_origin',
    'uci': 'required_ICU'
}

RENAME_COUNTRIES = {
    '97': 'xxa',
    '99': 'xxa',
    'afganistan': 'afg',
    'alemania': 'deu',
    'antartica': 'ata',
    'arabia saudita': 'sau',
    'archipialago de svalbard': 'sjm',
    'archipielago de svalbard': 'sjm',
    'argelia': 'dza',
    'argentina': 'arg',
    'armenia': 'arm',
    'ascensia3n': 'mex',
    'ascension': 'mex',
    'australia': 'aus',
    'austria': 'aut',
    'azerbaiyan - islas azores': 'aze',
    'balgica': 'bel',
    'bangladesh': 'bgd',
    'barbados': 'brb',
    'belice': 'blz',
    'bielorrusia': 'blr',
    'bolivia': 'bol',
    'bosnia y herzegovina': 'bih',
    'brasil': 'bra',
    'bulgaria': 'bgr',
    'burkina faso': 'bfa',
    'burundi': 'bdi',
    'camboya': 'khm',
    'cameraon': 'cmr',
    'cameroon': 'cmr',
    'camerun': 'cmr',
    'campione ditalia': 'che',
    'canada': 'can',
    'chile': 'chl',
    'china': 'chn',
    'colombia': 'col',
    'commonwealth de dominica': 'dma',
    'commonwealth de las bahamas': 'bhs',
    'congo': 'cog',
    'costa de marfil': 'civ',
    'croacia': 'hrv',
    'cuba': 'cub',
    'dinamarca': 'dnk',
    'ecuador': 'ecu',
    'egipto': 'egy',
    'el salvador': 'slv',
    'emiratos arabes unidos': 'are',
    'eritrea': 'eri',
    'eslovaquia': 'svk',
    'eslovenia': 'svn',
    'espaaa': 'esp',
    'espana': 'esp',
    'estado de kuwait': 'kwt',
    'estado libre asociado de puerto rico': 'pri',
    'estados unidos de amarica': 'usa',
    'estados unidos de america': 'usa',
    'estonia': 'est',
    'etiopaa': 'eth',
    'filipinas': 'phl',
    'finlandia': 'fin',
    'francia': 'fra',
    'georgia': 'geo',
    'ghana': 'gha',
    'gran bretaaa (reino unido)': 'gbr',
    'gran bretaña (reino unido)': 'gbr',
    'grecia': 'grc',
    'guadalupe': 'glp',
    'guatemala': 'gtm',
    'guinea': 'gin',
    'guinea ecuatorial': 'gnq',
    'guyana francesa': 'guf',
    'haita': 'hti',
    'haiti': 'hti',
    'holanda': 'nld',
    'hong kong': 'hkg',
    'hungraa': 'hun',
    'hungria': 'hun',
    'india': 'ind',
    'indonesia': 'idn',
    'iran': 'irn',
    'iraq': 'irq',
    'irlanda': 'irl',
    'islandia': 'isl',
    'islas menores alejadas de los estados unidos': 'umi',
    'islas vargenes britanicas': 'vgb',
    'islas vargenes de estados unidos de amarica': 'vir',
    'israel': 'isr',
    'italia': 'ita',
    'jamaica': 'jam',
    'japa3n': 'jpn',
    'japon': 'jpn',
    'kenia': 'ken',
    'labano': 'lbn',
    'letonia': 'lva',
    'libia': 'lby',
    'lituania': 'ltu',
    'macao': 'chn',
    'macedonia': 'mkd',
    'madeira': 'prt',
    'malasia': 'mys',
    'malta': 'mlt',
    'marruecos': 'mar',
    'maxico': 'mex',
    'mexico': 'mex',
    'micronesia': 'fsm',
    'moldavia': 'mda',
    'myanmar': 'mmr',
    'nager': 'ner',
    'nepal': 'npl',
    'nicaragua': 'nic',
    'nigeria': 'nga',
    'noruega': 'nor',
    'nueva zelandia': 'nzl',
    'otro': 'xxa',
    'paases de la ex-u.r.s.s., excepto ucrania y bielorusia': 'xxa',
    'pakistan': 'pak',
    'paraguay': 'pry',
    'perao': 'per',
    'peru': 'per',
    'polinesia francesa': 'pyf',
    'polonia': 'pol',
    'portugal': 'prt',
    'principado de ma3naco': 'mco',
    'principado de monaco': 'mco',
    'repaoblica centro africana': 'caf',
    'repaoblica checa y repaoblica eslovaca': 'cze',
    'repaoblica de albania': 'alb',
    'repaoblica de angola': 'ago',
    'repaoblica de chipre': 'cyp',
    'repaoblica de corea': 'kor',
    'repaoblica de costa rica': 'cri',
    'repaoblica de guyana': 'guy',
    'repaoblica de honduras': 'hnd',
    'repaoblica de mauricio': 'mus',
    'repaoblica de panama': 'pan',
    'repaoblica de taonez': 'tun',
    'repaoblica de trinidad y tobago': 'tto',
    'repaoblica democratica de corea': 'kor',
    'repaoblica dominicana': 'dom',
    'repaoblica oriental del uruguay': 'ury',
    'republica de angola': 'ago',
    'republica de corea': 'kor',
    'republica de costa rica': 'cri',
    'republica de honduras': 'hnd',
    'republica de mauricio': 'mus',
    'republica de panama': 'pan',
    'republica democratica del congo': 'cod',
    'república dominicana': 'dom',
    'republica oriental del uruguay': 'ury',
    'rhuanda': 'rwa',
    'rritrea': 'eri',
    'rumania': 'rou',
    'rusia': 'rus',
    'sark': 'chi',
    'se desconoce': 'xxa',
    'senegal': 'sen',
    'siria': 'syr',
    'somalia': 'som',
    'sudafrica': 'zaf',
    'suecia': 'swe',
    'suiza': 'che',
    'sultanaa de oman': 'omn',
    'surinam': 'sur',
    'taiwan': 'twn',
    'tanzania': 'tza',
    'tayikistan': 'tjk',
    'territorio britanico en el ocaano indico': 'iot',
    'thailandia': 'tha',
    'togo': 'tgo',
    'trieste': 'ita',
    'turquaa': 'tur',
    'turquia': 'tur',
    'ucrania': 'ukr',
    'uzbekistan': 'uzb',
    'venezuela': 'ven',
    'vietnam': 'vnm',
    'yemen democratica': 'ymd',
    'zaire': 'cod',
    'zimbabwe': 'zwe',
    'zona neutral': 'xxa',
    'papaoa nueva guinea': 'png',
    'gaba3n': 'gab',
    'campuchea democratica': 'khm'
}

def clean_tables(table_name: str):
    db_connector = Connector.fetch('clickhouse-database', open('../conns.yaml'))

    try:
        query_to_df(db_connector, raw_query=f"DROP TABLE {table_name}")
        print(f"Drop Table {table_name} Success!!")
    except:
        print(f"Table {table_name} does not exist.")
        pass