
rename_columns = {
    'fecha_actualizacion': 'updated_date',
    'origen': 'origin',
    'sector': 'type_health_institution_attended',
    'entidad_um': 'health_institution_attended_ent',
    'sexo': 'sex',
    'entidad_nac': 'patient_origin_ent_id',
    'tipo_paciente': 'patient_type',
    'fecha_ingreso': 'ingress_date',
    'fecha_sintomas': 'symptoms_date',
    'fecha_def': 'death_date',
    'intubado': 'intubated',
    'neumonia': 'pneumonia_diagnose',
    'edad': 'age',
    'nacionalidad': 'nationality',
    'embarazo': 'pregnancy',
    'habla_lengua_indig': 'speaks_indigenous_language',
    'diabetes': 'diabetes_diagnose',
    'epoc': 'COPD_diagnose',
    'asma': 'asthma_diagnose',
    'inmusupr': 'inmunosupresion_diagnose',
    'hipertension': 'hypertension_diagnose',
    'otra_com': 'diagnosis_another_disease',
    'cardiovascular': 'cardiovascular_diagnose',
    'obesidad': 'obesity_diagnose',
    'renal_cronica': 'chronic_kidney_failure_diagnose',
    'tabaquismo': 'smoking_diagnose',
    'otro_caso': 'contact_another_covid_case',
    'resultado': 'covid_positive',
    'migrante': 'migrant',
    'pais_nacionalidad': 'country_nationality',
    'pais_origen': 'country_origin',
    'uci': 'required_ICU'
}

rename_countries = {
    'México': 'mex',
    'Estados Unidos de América': 'usa',
    'Ecuador': 'ecu',
    'España': 'esp',
    'El Salvador': 'slv',
    'Brasil': 'bra',
    'Guatemala': 'gtm',
    'Trieste': 'ita',
    'Belice': 'blz',
    'Zona Neutral': '',
    'Argentina': 'arg',
    'Nicaragua': 'nic',
    'Venezuela': 'ven',
    'Cuba': 'cub',
    'Colombia': 'col',
    'Francia': 'fra',
    'República de Honduras': 'hnd',
    'Turquía': 'tur',
    'Macao': 'chn',
    'Bolivia': 'bol',
    'Chile': 'chl',
    'Camerún': 'cmr',
    'Japón': 'jpn',
    'Archipiélago de Svalbard': 'sjm',
    'República Dominicana': 'dom',
    'Perú': 'per',
    'Canadá': 'can',
    'Gran Bretaña (Reino Unido)': 'gbr',
    'Italia': 'ita',
    'Suiza': 'che',
    'Alemania': 'deu',
    'República de Panamá': 'pan',
    'Polonia': 'pol',
    'China': 'chn',
    'Israel': 'isr',
    'Irlanda': 'irl',
    'República de Angola': 'ago',
    'Australia': 'aus',
    'Suecia': 'swe',
    'Egipto': 'egy',
    'Portugal': 'prt',
    'Commonwealth de Dominica': 'dma',
    'Hungría': 'hun',
    'Ucrania': 'ukr',
    'Pakistán': 'pak',
    'Eritrea': 'eri',
    'Austria': 'aut',
    'Grecia': 'grc',
    'República de Corea': 'kor',
    'Micronesia': 'fsm',
    'Haití': 'hti',
    'Rusia': 'rus',
    'Rumania': 'rou',
    'Malasia': 'mys',
    'Ascensión': 'mex',
    'Irán': 'irn',
    'India': 'ind',
    'Zimbabwe': 'zwe',
    'Holanda': 'nld',
    'República de Mauricio': 'mus',
    'Principado de Mónaco': 'mco',
    'República de Costa Rica': 'cri',
    'República Oriental del Uruguay': 'ury',
    'Argelia': 'dza',
    'Bosnia y Herzegovina': 'bih',
    'Noruega': 'nor',
    'Otro': 'xxa',
    '99': 'xxa',
    '97': 'xxa'
}
