
rename_columns = {
    'fecha_actualizacion': 'updated_date',
    'origen': 'origin',
    'sector': 'type_health_institution_attended',
    'entidad_um': 'health_institution_attended_ent',
    'sexo': 'sex',
    'entidad_nac': 'patient_origin_ent_id',
    'tipo_paciente': 'patient_type',
    'fecha_ingreso': 'ingress_date',
    'fecha_sintomas': 'symptoms_date',
    'fecha_def': 'death_date',
    'intubado': 'intubated',
    'neumonia': 'pneumonia_diagnose',
    'edad': 'age',
    'nacionalidad': 'nationality',
    'embarazo': 'pregnancy',
    'habla_lengua_indig': 'speaks_indigenous_language',
    'diabetes': 'diabetes_diagnose',
    'epoc': 'COPD_diagnose',
    'asma': 'asthma_diagnose',
    'inmusupr': 'inmunosupresion_diagnose',
    'hipertension': 'hypertension_diagnose',
    'otra_com': 'diagnosis_another_disease',
    'cardiovascular': 'cardiovascular_diagnose',
    'obesidad': 'obesity_diagnose',
    'renal_cronica': 'chronic_kidney_failure_diagnose',
    'tabaquismo': 'smoking_diagnose',
    'otro_caso': 'contact_another_covid_case',
    'resultado': 'covid_positive',
    'migrante': 'migrant',
    'pais_nacionalidad': 'country_nationality',
    'pais_origen': 'country_origin',
    'uci': 'required_ICU'
}

rename_countries = {
    'mexico': 'mex',
    'maxico': 'mex',
    'estados unidos de america': 'usa',
    'estados unidos de amarica': 'usa',
    'ecuador': 'ecu',
    'espana': 'esp',
    'espaaa': 'esp',
    'el salvador': 'slv',
    'brasil': 'bra',
    'guatemala': 'gtm',
    'trieste': 'ita',
    'belice': 'blz',
    'argentina': 'arg',
    'nicaragua': 'nic',
    'venezuela': 'ven',
    'cuba': 'cub',
    'colombia': 'col',
    'francia': 'fra',
    'republica de honduras': 'hnd',
    'repaoblica de honduras': 'hnd',
    'turquia': 'tur',
    'turquaa': 'tur',
    'macao': 'chn',
    'bolivia': 'bol',
    'chile': 'chl',
    'camerun': 'cmr',
    'japon': 'jpn',
    'japa3n': 'jpn',
    'labano': 'lbn',
    'archipielago de svalbard': 'sjm',
    'archipialago de svalbard': 'sjm',
    'república dominicana': 'dom',
    'repaoblica dominicana': 'dom',
    'peru': 'per',
    'perao': 'per',
    'canada': 'can',
    'gran bretaña (reino unido)': 'gbr',
    'gran bretaaa (reino unido)': 'gbr',
    'italia': 'ita',
    'suiza': 'che',
    'alemania': 'deu',
    'republica de panama': 'pan',
    'repaoblica de panama': 'pan',
    'polonia': 'pol',
    'china': 'chn',
    'israel': 'isr',
    'irlanda': 'irl',
    'republica de angola': 'ago',
    'repaoblica de angola': 'ago',
    'australia': 'aus',
    'suecia': 'swe',
    'egipto': 'egy',
    'portugal': 'prt',
    'commonwealth de dominica': 'dma',
    'cameroon': 'cmr',
    'cameraon': 'cmr',
    'hungria': 'hun',
    'hungraa': 'hun',
    'ucrania': 'ukr',
    'paraguay': 'pry',
    'pakistan': 'pak',
    'rritrea': 'eri',
    'austria': 'aut',
    'grecia': 'grc',
    'islandia': 'isl',
    'republica de corea': 'kor',
    'repaoblica de corea': 'kor',
    'micronesia': 'fsm',
    'eritrea': 'eri',
    'haiti': 'hti',
    'haita': 'hti',
    'rusia': 'rus',
    'rumania': 'rou',
    'malasia': 'mys',
    'ascension': 'mex',
    'iran': 'irn',
    'india': 'ind',
    'zimbabwe': 'zwe',
    'holanda': 'nld',
    'republica de mauricio': 'mus',
    'repaoblica de mauricio': 'mus',
    'principado de monaco': 'mco',
    'principado de ma3naco': 'mco',
    'republica de costa rica': 'cri',
    'repaoblica de costa rica': 'cri',
    'republica oriental del uruguay': 'ury',
    'repaoblica oriental del uruguay': 'ury',
    'argelia': 'dza',
    'bosnia y herzegovina': 'bih',
    'noruega': 'nor',
    'dinamarca': 'dnk',
    'ascensia3n': 'mex',
    'zona neutral': 'xxa',
    'otro': 'xxa',
    '99': 'xxa',
    '97': 'xxa'
}
